server:
  port: 80
spring:
  servlet:
    multipart:
     enabled: true
     max-file-size: 20MB
     max-request-size: 20MB
  application:
    name: blog
  mvc:
    #访问静态资源
    static-path-pattern: /static/**
  thymeleaf:
    #    view-names: /*
    #配置访问模版的路径前缀
    prefix: classpath:/templates/
    #配置访问模版的路径后缀
    suffix: .html
    #使用模版路径
    check-template-location: true
    #模版的编码为UTF-8
    encoding: UTF-8
    #模版的类型为text/templates.html
    servlet:
      content-type: text/html
    #使用html5相关标签
    mode: HTML5
    #不使用模版缓存
    cache: false
    #配置阿里巴巴数据源的四大件
  mail:
    username: 改成自己的qq号
    password: 密码是qq邮箱开发者的一串验证码
    host: smtp.qq.com
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory



  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    # 连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
  profiles:
    active: dev

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#标准日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.blog.bean

swagger:
  basePackage: com.blog.controller
  title: 何正
  description: swagger文档
  version: V1.0


#日志记录
logging:
  level:
    root: warn
    com.blog: info
  file: log/blog.log
